/**
 * @packageDocumentation
 * @module api.functional.api.auth.signin
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { SignInBody } from "../../../../structures/SignInBody";
import type { SignInResponse } from "../../../../structures/SignInResponse";

/**
 * @controller AuthController.signIn
 * @path POST /api/auth/signin
 * @accessor api.functional.api.auth.signin.signIn
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function signIn(
  connection: IConnection,
  body: signIn.Body,
): Promise<signIn.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...signIn.METADATA,
      template: signIn.METADATA.path,
      path: signIn.path(),
    },
    body,
  );
}
export namespace signIn {
  export type Body = SignInBody;
  export type Output = SignInResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/auth/signin",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/auth/signin";
}
