/**
 * @packageDocumentation
 * @module api.functional.api.author
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Format } from "typia/lib/tags/Format";

import type { CreateAuthorBody } from "../../../structures/CreateAuthorBody";
import type { CreateAuthorResponse } from "../../../structures/CreateAuthorResponse";
import type { GetAuthorResponse } from "../../../structures/GetAuthorResponse";
import type { GetAuthorsResponse } from "../../../structures/GetAuthorsResponse";
import type { Partial__type } from "../../../structures/Partial__type";
import type { PartialCreateAuthorBody } from "../../../structures/PartialCreateAuthorBody";

/**
 * @controller AuthorController.createAuthor
 * @path POST /api/author
 * @accessor api.functional.api.author.createAuthor
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createAuthor(
  connection: IConnection,
  body: createAuthor.Body,
): Promise<createAuthor.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createAuthor.METADATA,
      template: createAuthor.METADATA.path,
      path: createAuthor.path(),
    },
    body,
  );
}
export namespace createAuthor {
  export type Body = CreateAuthorBody;
  export type Output = CreateAuthorResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/author",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/author";
}

/**
 * @controller AuthorController.updateAuthor
 * @path PATCH /api/author/:id
 * @accessor api.functional.api.author.updateAuthor
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateAuthor(
  connection: IConnection,
  id: string & Format<"uuid">,
  body: updateAuthor.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateAuthor.METADATA,
      template: updateAuthor.METADATA.path,
      path: updateAuthor.path(id),
    },
    body,
  );
}
export namespace updateAuthor {
  export type Body = PartialCreateAuthorBody;

  export const METADATA = {
    method: "PATCH",
    path: "/api/author/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/author/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller AuthorController.deleteAuthor
 * @path DELETE /api/author/:id
 * @accessor api.functional.api.author.deleteAuthor
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteAuthor(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteAuthor.METADATA,
    template: deleteAuthor.METADATA.path,
    path: deleteAuthor.path(id),
  });
}
export namespace deleteAuthor {
  export const METADATA = {
    method: "DELETE",
    path: "/api/author/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/author/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller AuthorController.getAllAuthors
 * @path GET /api/author
 * @accessor api.functional.api.author.getAllAuthors
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllAuthors(
  connection: IConnection,
  query: getAllAuthors.Query,
): Promise<getAllAuthors.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAllAuthors.METADATA,
    template: getAllAuthors.METADATA.path,
    path: getAllAuthors.path(query),
  });
}
export namespace getAllAuthors {
  export type Query = Partial__type;
  export type Output = GetAuthorsResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/author",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/author";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * @controller AuthorController.findAuthorById
 * @path GET /api/author/:id
 * @accessor api.functional.api.author.findAuthorById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAuthorById(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<findAuthorById.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAuthorById.METADATA,
    template: findAuthorById.METADATA.path,
    path: findAuthorById.path(id),
  });
}
export namespace findAuthorById {
  export type Output = GetAuthorResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/author/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/author/${encodeURIComponent(id?.toString() ?? "null")}`;
}
