/**
 * @packageDocumentation
 * @module api.functional.api.author
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Format } from "typia/lib/tags/Format";

import type { CreateAuthorBody } from "../../../structures/CreateAuthorBody";
import type { CreateAuthorResponse } from "../../../structures/CreateAuthorResponse";
import type { DeleteAuthorResponse } from "../../../structures/DeleteAuthorResponse";

/**
 * @controller AuthorController.createAuthor
 * @path POST /api/author
 * @accessor api.functional.api.author.createAuthor
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createAuthor(
  connection: IConnection,
  body: createAuthor.Body,
): Promise<createAuthor.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createAuthor.METADATA,
      template: createAuthor.METADATA.path,
      path: createAuthor.path(),
    },
    body,
  );
}
export namespace createAuthor {
  export type Body = CreateAuthorBody;
  export type Output = CreateAuthorResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/author",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/author";
}

/**
 * @controller AuthorController.deleteAuthor
 * @path DELETE /api/author/:id
 * @accessor api.functional.api.author.deleteAuthor
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteAuthor(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<deleteAuthor.Output> {
  return PlainFetcher.fetch(connection, {
    ...deleteAuthor.METADATA,
    template: deleteAuthor.METADATA.path,
    path: deleteAuthor.path(id),
  });
}
export namespace deleteAuthor {
  export type Output = DeleteAuthorResponse;

  export const METADATA = {
    method: "DELETE",
    path: "/api/author/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/author/${encodeURIComponent(id?.toString() ?? "null")}`;
}
