/**
 * @packageDocumentation
 * @module api.functional.api.loan
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Format } from "typia/lib/tags/Format";

import type { CreateLoanResponse } from "../../../structures/CreateLoanResponse";
import type { GetLoansResponse } from "../../../structures/GetLoansResponse";

/**
 * @controller LoanController.createLoan
 * @path POST /api/loan
 * @accessor api.functional.api.loan.createLoan
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createLoan(
  connection: IConnection,
): Promise<createLoan.Output> {
  return PlainFetcher.fetch(connection, {
    ...createLoan.METADATA,
    template: createLoan.METADATA.path,
    path: createLoan.path(),
  });
}
export namespace createLoan {
  export type Output = CreateLoanResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/loan",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/loan";
}

/**
 * @controller LoanController.getLoans
 * @path GET /api/loan
 * @accessor api.functional.api.loan.getLoans
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLoans(
  connection: IConnection,
  cursor?: undefined | string,
  limit?: undefined | number,
  state?: undefined | string,
): Promise<getLoans.Output> {
  return PlainFetcher.fetch(connection, {
    ...getLoans.METADATA,
    template: getLoans.METADATA.path,
    path: getLoans.path(cursor, limit, state),
  });
}
export namespace getLoans {
  export type Output = GetLoansResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/loan",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    cursor?: undefined | string,
    limit?: undefined | number,
    state?: undefined | string,
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      cursor: cursor,
      limit: limit,
      state: state,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/loan";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * @controller LoanController.deleteLoan
 * @path DELETE /api/loan/:id
 * @accessor api.functional.api.loan.deleteLoan
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteLoan(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteLoan.METADATA,
    template: deleteLoan.METADATA.path,
    path: deleteLoan.path(id),
  });
}
export namespace deleteLoan {
  export const METADATA = {
    method: "DELETE",
    path: "/api/loan/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/loan/${encodeURIComponent(id?.toString() ?? "null")}`;
}
