services:
  postgres:
    ports:
      - '5432:5432'

  redis:
    ports:
      - '6379:6379'

  rustfs:
    ports:
      - '9000:9000'
      - '9001:9001'

  api:
    environment:
      CORS_ORIGINS: http://localhost:3000

  web:
    ports:
      - '3000:3000'
