services:
  postgres:
    env_file: .env
    ports:
      - 5432:5432

  redis:
    env_file: .env
    ports:
      - 6379:6379

  rustfs:
    env_file: .env
    ports:
      - 9000:9000
      - 9001:9001
