/**
 * @packageDocumentation
 * @module api.functional.api.auth.password
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { ChangePasswordBody } from "../../../../structures/ChangePasswordBody";

/**
 * @controller AuthController.changePassword
 * @path PUT /api/auth/password
 * @accessor api.functional.api.auth.password.changePassword
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function changePassword(
  connection: IConnection,
  body: changePassword.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...changePassword.METADATA,
      template: changePassword.METADATA.path,
      path: changePassword.path(),
    },
    body,
  );
}
export namespace changePassword {
  export type Body = ChangePasswordBody;

  export const METADATA = {
    method: "PUT",
    path: "/api/auth/password",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = () => "/api/auth/password";
}
