/**
 * @packageDocumentation
 * @module api.functional.api.auth.signup
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { SignUpBody } from "../../../../structures/SignUpBody";
import type { SignUpResponse } from "../../../../structures/SignUpResponse";

/**
 * @controller AuthController.signUp
 * @path POST /api/auth/signup
 * @accessor api.functional.api.auth.signup.signUp
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function signUp(
  connection: IConnection,
  body: signUp.Body,
): Promise<signUp.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...signUp.METADATA,
      template: signUp.METADATA.path,
      path: signUp.path(),
    },
    body,
  );
}
export namespace signUp {
  export type Body = SignUpBody;
  export type Output = SignUpResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/auth/signup",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/auth/signup";
}
