/**
 * @packageDocumentation
 * @module api.functional.api.session
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { GetSessionsResponse } from "../../../structures/GetSessionsResponse";

/**
 * @controller SessionController.getAllSessions
 * @path GET /api/session
 * @accessor api.functional.api.session.getAllSessions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllSessions(
  connection: IConnection,
): Promise<getAllSessions.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAllSessions.METADATA,
    template: getAllSessions.METADATA.path,
    path: getAllSessions.path(),
  });
}
export namespace getAllSessions {
  export type Output = GetSessionsResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/session",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/session";
}

/**
 * @controller SessionController.revokeSession
 * @path DELETE /api/session/:id
 * @accessor api.functional.api.session.revokeSession
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function revokeSession(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...revokeSession.METADATA,
    template: revokeSession.METADATA.path,
    path: revokeSession.path(id),
  });
}
export namespace revokeSession {
  export const METADATA = {
    method: "DELETE",
    path: "/api/session/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string) =>
    `/api/session/${encodeURIComponent(id?.toString() ?? "null")}`;
}
