/**
 * @packageDocumentation
 * @module api.functional.api.reservation
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { CreateReservationBody } from "../../../structures/CreateReservationBody";
import type { CreateReservationResponse } from "../../../structures/CreateReservationResponse";
import type { GetReservationsResponse } from "../../../structures/GetReservationsResponse";

/**
 * @controller ReservationController.createReservation
 * @path POST /api/reservation
 * @accessor api.functional.api.reservation.createReservation
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createReservation(
  connection: IConnection,
  data: createReservation.Body,
): Promise<createReservation.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createReservation.METADATA,
      template: createReservation.METADATA.path,
      path: createReservation.path(),
    },
    data,
  );
}
export namespace createReservation {
  export type Body = CreateReservationBody;
  export type Output = CreateReservationResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/reservation",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/reservation";
}

/**
 * @controller ReservationController.getReservations
 * @path GET /api/reservation
 * @accessor api.functional.api.reservation.getReservations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getReservations(
  connection: IConnection,
  cursor?: undefined | string,
  limit?: undefined | number,
): Promise<getReservations.Output> {
  return PlainFetcher.fetch(connection, {
    ...getReservations.METADATA,
    template: getReservations.METADATA.path,
    path: getReservations.path(cursor, limit),
  });
}
export namespace getReservations {
  export type Output = GetReservationsResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/reservation",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    cursor?: undefined | string,
    limit?: undefined | number,
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      cursor: cursor,
      limit: limit,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/reservation";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
