/**
 * @packageDocumentation
 * @module api.functional.api.category
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { CreateCategoryBody } from "../../../structures/CreateCategoryBody";
import type { CreateCategoryResponse } from "../../../structures/CreateCategoryResponse";

/**
 * @controller CategoryController.createCategory
 * @path POST /api/category
 * @accessor api.functional.api.category.createCategory
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createCategory(
  connection: IConnection,
  body: createCategory.Body,
): Promise<createCategory.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createCategory.METADATA,
      template: createCategory.METADATA.path,
      path: createCategory.path(),
    },
    body,
  );
}
export namespace createCategory {
  export type Body = CreateCategoryBody;
  export type Output = CreateCategoryResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/category",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/category";
}
