/**
 * @packageDocumentation
 * @module api.functional.api.category
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Format } from "typia/lib/tags/Format";

import type { CreateCategoryBody } from "../../../structures/CreateCategoryBody";
import type { CreateCategoryResponse } from "../../../structures/CreateCategoryResponse";
import type { GetCategoryResponse } from "../../../structures/GetCategoryResponse";
import type { PartialCreateCategoryBody } from "../../../structures/PartialCreateCategoryBody";

/**
 * @controller CategoryController.createCategory
 * @path POST /api/category
 * @accessor api.functional.api.category.createCategory
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createCategory(
  connection: IConnection,
  body: createCategory.Body,
): Promise<createCategory.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createCategory.METADATA,
      template: createCategory.METADATA.path,
      path: createCategory.path(),
    },
    body,
  );
}
export namespace createCategory {
  export type Body = CreateCategoryBody;
  export type Output = CreateCategoryResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/category",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/category";
}

/**
 * @controller CategoryController.getCategory
 * @path GET /api/category/:id
 * @accessor api.functional.api.category.getCategory
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getCategory(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<getCategory.Output> {
  return PlainFetcher.fetch(connection, {
    ...getCategory.METADATA,
    template: getCategory.METADATA.path,
    path: getCategory.path(id),
  });
}
export namespace getCategory {
  export type Output = GetCategoryResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/category/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/category/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller CategoryController.updateCategory
 * @path PATCH /api/category/:id
 * @accessor api.functional.api.category.updateCategory
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateCategory(
  connection: IConnection,
  id: string & Format<"uuid">,
  body: updateCategory.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateCategory.METADATA,
      template: updateCategory.METADATA.path,
      path: updateCategory.path(id),
    },
    body,
  );
}
export namespace updateCategory {
  export type Body = PartialCreateCategoryBody;

  export const METADATA = {
    method: "PATCH",
    path: "/api/category/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/category/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller CategoryController.deleteCategory
 * @path DELETE /api/category/:id
 * @accessor api.functional.api.category.deleteCategory
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteCategory(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteCategory.METADATA,
    template: deleteCategory.METADATA.path,
    path: deleteCategory.path(id),
  });
}
export namespace deleteCategory {
  export const METADATA = {
    method: "DELETE",
    path: "/api/category/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/category/${encodeURIComponent(id?.toString() ?? "null")}`;
}
