/**
 * @packageDocumentation
 * @module api.functional.api.user.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { GetMeResponse } from "../../../../structures/GetMeResponse";
import type { UpdateUserBody } from "../../../../structures/UpdateUserBody";

/**
 * @controller UserController.me
 * @path GET /api/user/me
 * @accessor api.functional.api.user.me.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function me(connection: IConnection): Promise<me.Output> {
  return PlainFetcher.fetch(connection, {
    ...me.METADATA,
    template: me.METADATA.path,
    path: me.path(),
  });
}
export namespace me {
  export type Output = GetMeResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/user/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/user/me";
}

/**
 * @controller UserController.updateMe
 * @path PATCH /api/user/me
 * @accessor api.functional.api.user.me.updateMe
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateMe(
  connection: IConnection,
  body: updateMe.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateMe.METADATA,
      template: updateMe.METADATA.path,
      path: updateMe.path(),
    },
    body,
  );
}
export namespace updateMe {
  export type Body = UpdateUserBody;

  export const METADATA = {
    method: "PATCH",
    path: "/api/user/me",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = () => "/api/user/me";
}
