/**
 * @packageDocumentation
 * @module api.functional.api.user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

export * as me from "./me/index";

/**
 * @controller UserController.getAllUsers
 * @path GET /api/user
 * @accessor api.functional.api.user.getAllUsers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllUsers(
  connection: IConnection,
  search?: undefined | string,
  page?: undefined | number,
  limit?: undefined | number,
): Promise<getAllUsers.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAllUsers.METADATA,
    template: getAllUsers.METADATA.path,
    path: getAllUsers.path(search, page, limit),
  });
}
export namespace getAllUsers {
  export type Output = {
    message: string;
    meta: {
      total: number;
    };
    data: {
      id: string;
      email: string;
      firstName: string;
      lastName: null | string;
      photoFileName: null | string;
      role: "ADMIN" | "LIBRARIAN" | "MEMBER";
    }[];
  };

  export const METADATA = {
    method: "GET",
    path: "/api/user",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    search?: undefined | string,
    page?: undefined | number,
    limit?: undefined | number,
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      search: search,
      page: page,
      limit: limit,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/user";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
