/**
 * @packageDocumentation
 * @module api.functional.api.publisher
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Format } from "typia/lib/tags/Format";

import type { CreatePublisherBody } from "../../../structures/CreatePublisherBody";
import type { CreatePublisherResponse } from "../../../structures/CreatePublisherResponse";
import type { DeletePublisherResponse } from "../../../structures/DeletePublisherResponse";

/**
 * @controller PublisherController.createPublisher
 * @path POST /api/publisher
 * @accessor api.functional.api.publisher.createPublisher
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createPublisher(
  connection: IConnection,
  body: createPublisher.Body,
): Promise<createPublisher.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createPublisher.METADATA,
      template: createPublisher.METADATA.path,
      path: createPublisher.path(),
    },
    body,
  );
}
export namespace createPublisher {
  export type Body = CreatePublisherBody;
  export type Output = CreatePublisherResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/publisher",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/publisher";
}

/**
 * @controller PublisherController.deletePublisher
 * @path DELETE /api/publisher/:id
 * @accessor api.functional.api.publisher.deletePublisher
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deletePublisher(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<deletePublisher.Output> {
  return PlainFetcher.fetch(connection, {
    ...deletePublisher.METADATA,
    template: deletePublisher.METADATA.path,
    path: deletePublisher.path(id),
  });
}
export namespace deletePublisher {
  export type Output = DeletePublisherResponse;

  export const METADATA = {
    method: "DELETE",
    path: "/api/publisher/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/publisher/${encodeURIComponent(id?.toString() ?? "null")}`;
}
