/**
 * @packageDocumentation
 * @module api.functional.api.publisher
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Format } from "typia/lib/tags/Format";

import type { CreatePublisherBody } from "../../../structures/CreatePublisherBody";
import type { CreatePublisherResponse } from "../../../structures/CreatePublisherResponse";
import type { GetPublisherResponse } from "../../../structures/GetPublisherResponse";
import type { GetPublishersResponse } from "../../../structures/GetPublishersResponse";
import type { Partial__type } from "../../../structures/Partial__type";
import type { PartialCreatePublisherBody } from "../../../structures/PartialCreatePublisherBody";

/**
 * @controller PublisherController.createPublisher
 * @path POST /api/publisher
 * @accessor api.functional.api.publisher.createPublisher
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createPublisher(
  connection: IConnection,
  body: createPublisher.Body,
): Promise<createPublisher.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createPublisher.METADATA,
      template: createPublisher.METADATA.path,
      path: createPublisher.path(),
    },
    body,
  );
}
export namespace createPublisher {
  export type Body = CreatePublisherBody;
  export type Output = CreatePublisherResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/publisher",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/publisher";
}

/**
 * @controller PublisherController.getPublisher
 * @path GET /api/publisher/:id
 * @accessor api.functional.api.publisher.getPublisher
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getPublisher(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<getPublisher.Output> {
  return PlainFetcher.fetch(connection, {
    ...getPublisher.METADATA,
    template: getPublisher.METADATA.path,
    path: getPublisher.path(id),
  });
}
export namespace getPublisher {
  export type Output = GetPublisherResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/publisher/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/publisher/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller PublisherController.updatePublisher
 * @path PATCH /api/publisher/:id
 * @accessor api.functional.api.publisher.updatePublisher
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updatePublisher(
  connection: IConnection,
  id: string & Format<"uuid">,
  body: updatePublisher.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updatePublisher.METADATA,
      template: updatePublisher.METADATA.path,
      path: updatePublisher.path(id),
    },
    body,
  );
}
export namespace updatePublisher {
  export type Body = PartialCreatePublisherBody;

  export const METADATA = {
    method: "PATCH",
    path: "/api/publisher/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/publisher/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller PublisherController.deletePublisher
 * @path DELETE /api/publisher/:id
 * @accessor api.functional.api.publisher.deletePublisher
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deletePublisher(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deletePublisher.METADATA,
    template: deletePublisher.METADATA.path,
    path: deletePublisher.path(id),
  });
}
export namespace deletePublisher {
  export const METADATA = {
    method: "DELETE",
    path: "/api/publisher/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/publisher/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller PublisherController.getAllPublishers
 * @path GET /api/publisher
 * @accessor api.functional.api.publisher.getAllPublishers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllPublishers(
  connection: IConnection,
  query: getAllPublishers.Query,
): Promise<getAllPublishers.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAllPublishers.METADATA,
    template: getAllPublishers.METADATA.path,
    path: getAllPublishers.path(query),
  });
}
export namespace getAllPublishers {
  export type Query = Partial__type.o2;
  export type Output = GetPublishersResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/publisher",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/publisher";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
