/**
 * @packageDocumentation
 * @module api.functional.api.book_copy
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Format } from "typia/lib/tags/Format";

import type { CreateBookCopyBody } from "../../../structures/CreateBookCopyBody";
import type { CreateBookCopyResponse } from "../../../structures/CreateBookCopyResponse";
import type { GetBookCopiesResponse } from "../../../structures/GetBookCopiesResponse";
import type { GetBookCopyResponse } from "../../../structures/GetBookCopyResponse";
import type { PartialCreateBookCopyBody } from "../../../structures/PartialCreateBookCopyBody";

/**
 * @controller BookCopyController.createBookCopy
 * @path POST /api/book-copy
 * @accessor api.functional.api.book_copy.createBookCopy
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createBookCopy(
  connection: IConnection,
  body: createBookCopy.Body,
): Promise<createBookCopy.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createBookCopy.METADATA,
      template: createBookCopy.METADATA.path,
      path: createBookCopy.path(),
    },
    body,
  );
}
export namespace createBookCopy {
  export type Body = CreateBookCopyBody;
  export type Output = CreateBookCopyResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/book-copy",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/book-copy";
}

/**
 * @controller BookCopyController.getBookCopy
 * @path GET /api/book-copy/:id
 * @accessor api.functional.api.book_copy.getBookCopy
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getBookCopy(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<getBookCopy.Output> {
  return PlainFetcher.fetch(connection, {
    ...getBookCopy.METADATA,
    template: getBookCopy.METADATA.path,
    path: getBookCopy.path(id),
  });
}
export namespace getBookCopy {
  export type Output = GetBookCopyResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/book-copy/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/book-copy/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller BookCopyController.updateBookCopy
 * @path PATCH /api/book-copy/:id
 * @accessor api.functional.api.book_copy.updateBookCopy
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateBookCopy(
  connection: IConnection,
  id: string & Format<"uuid">,
  body: updateBookCopy.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateBookCopy.METADATA,
      template: updateBookCopy.METADATA.path,
      path: updateBookCopy.path(id),
    },
    body,
  );
}
export namespace updateBookCopy {
  export type Body = PartialCreateBookCopyBody;

  export const METADATA = {
    method: "PATCH",
    path: "/api/book-copy/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/book-copy/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller BookCopyController.deleteBookCopy
 * @path DELETE /api/book-copy/:id
 * @accessor api.functional.api.book_copy.deleteBookCopy
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteBookCopy(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteBookCopy.METADATA,
    template: deleteBookCopy.METADATA.path,
    path: deleteBookCopy.path(id),
  });
}
export namespace deleteBookCopy {
  export const METADATA = {
    method: "DELETE",
    path: "/api/book-copy/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/book-copy/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller BookCopyController.searchBookCopies
 * @path GET /api/book-copy
 * @accessor api.functional.api.book_copy.searchBookCopies
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function searchBookCopies(
  connection: IConnection,
  search?: undefined | string,
  page?: undefined | number,
  limit?: undefined | number,
  status?: undefined | "AVAILABLE" | "BORROWED",
  condition?: undefined | "NEW" | "GOOD" | "WORN" | "DAMAGED" | "LOST",
): Promise<searchBookCopies.Output> {
  return PlainFetcher.fetch(connection, {
    ...searchBookCopies.METADATA,
    template: searchBookCopies.METADATA.path,
    path: searchBookCopies.path(search, page, limit, status, condition),
  });
}
export namespace searchBookCopies {
  export type Output = GetBookCopiesResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/book-copy",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    search?: undefined | string,
    page?: undefined | number,
    limit?: undefined | number,
    status?: undefined | "AVAILABLE" | "BORROWED",
    condition?: undefined | "NEW" | "GOOD" | "WORN" | "DAMAGED" | "LOST",
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      search: search,
      page: page,
      limit: limit,
      status: status,
      condition: condition,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/book-copy";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
