/**
 * @packageDocumentation
 * @module api.functional.api.book_copy
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { CreateBookCopyBody } from "../../../structures/CreateBookCopyBody";
import type { CreateBookCopyResponse } from "../../../structures/CreateBookCopyResponse";

/**
 * @controller BookCopyController.createBookCopy
 * @path POST /api/book-copy
 * @accessor api.functional.api.book_copy.createBookCopy
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createBookCopy(
  connection: IConnection,
  body: createBookCopy.Body,
): Promise<createBookCopy.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createBookCopy.METADATA,
      template: createBookCopy.METADATA.path,
      path: createBookCopy.path(),
    },
    body,
  );
}
export namespace createBookCopy {
  export type Body = CreateBookCopyBody;
  export type Output = CreateBookCopyResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/book-copy",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/book-copy";
}
