/**
 * @packageDocumentation
 * @module api.functional.api.book
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Format } from "typia/lib/tags/Format";

import type { CreateBookBody } from "../../../structures/CreateBookBody";
import type { CreateBookResponse } from "../../../structures/CreateBookResponse";
import type { GetBookResponse } from "../../../structures/GetBookResponse";
import type { PartialCreateBookBody } from "../../../structures/PartialCreateBookBody";

/**
 * @controller BookController.createBook
 * @path POST /api/book
 * @accessor api.functional.api.book.createBook
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createBook(
  connection: IConnection,
  body: createBook.Body,
): Promise<createBook.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createBook.METADATA,
      template: createBook.METADATA.path,
      path: createBook.path(),
    },
    body,
  );
}
export namespace createBook {
  export type Body = CreateBookBody;
  export type Output = CreateBookResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/book",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/book";
}

/**
 * @controller BookController.getBook
 * @path GET /api/book/:id
 * @accessor api.functional.api.book.getBook
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getBook(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<getBook.Output> {
  return PlainFetcher.fetch(connection, {
    ...getBook.METADATA,
    template: getBook.METADATA.path,
    path: getBook.path(id),
  });
}
export namespace getBook {
  export type Output = GetBookResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/book/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/book/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller BookController.updateBook
 * @path PATCH /api/book/:id
 * @accessor api.functional.api.book.updateBook
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateBook(
  connection: IConnection,
  id: string & Format<"uuid">,
  body: updateBook.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateBook.METADATA,
      template: updateBook.METADATA.path,
      path: updateBook.path(id),
    },
    body,
  );
}
export namespace updateBook {
  export type Body = PartialCreateBookBody;

  export const METADATA = {
    method: "PATCH",
    path: "/api/book/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/book/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller BookController.deleteBook
 * @path DELETE /api/book/:id
 * @accessor api.functional.api.book.deleteBook
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteBook(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteBook.METADATA,
    template: deleteBook.METADATA.path,
    path: deleteBook.path(id),
  });
}
export namespace deleteBook {
  export const METADATA = {
    method: "DELETE",
    path: "/api/book/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/api/book/${encodeURIComponent(id?.toString() ?? "null")}`;
}
