/**
 * @packageDocumentation
 * @module api.functional.api.book.search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { SearchBooksQuery } from "../../../../structures/SearchBooksQuery";
import type { SearchBooksResponse } from "../../../../structures/SearchBooksResponse";

/**
 * @controller BookController.searchBooks
 * @path GET /api/book/search
 * @accessor api.functional.api.book.search.searchBooks
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function searchBooks(
  connection: IConnection,
  query: searchBooks.Query,
): Promise<searchBooks.Output> {
  return PlainFetcher.fetch(connection, {
    ...searchBooks.METADATA,
    template: searchBooks.METADATA.path,
    path: searchBooks.path(query),
  });
}
export namespace searchBooks {
  export type Query = SearchBooksQuery;
  export type Output = SearchBooksResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/book/search",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/book/search";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
