/**
 * @packageDocumentation
 * @module api.functional.api.auth.signout
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller AuthController.signOut
 * @path POST /api/auth/signout
 * @accessor api.functional.api.auth.signout.signOut
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function signOut(connection: IConnection): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...signOut.METADATA,
    template: signOut.METADATA.path,
    path: signOut.path(),
  });
}
export namespace signOut {
  export const METADATA = {
    method: "POST",
    path: "/api/auth/signout",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = () => "/api/auth/signout";
}
