/**
 * @packageDocumentation
 * @module api.functional.api.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { SignInBody } from "../../../structures/SignInBody";
import type { SignInResponse } from "../../../structures/SignInResponse";
import type { SignUpBody } from "../../../structures/SignUpBody";
import type { SignUpResponse } from "../../../structures/SignUpResponse";

/**
 * @throws 409 Account with provided email already exists
 * @controller AuthController.signup
 * @path POST /api/auth/signup
 * @accessor api.functional.api.auth.signup
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function signup(
  connection: IConnection,
  body: signup.Body,
): Promise<signup.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...signup.METADATA,
      template: signup.METADATA.path,
      path: signup.path(),
    },
    body,
  );
}
export namespace signup {
  export type Body = SignUpBody;
  export type Output = SignUpResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/auth/signup",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/auth/signup";
}

/**
 * @controller AuthController.signin
 * @path POST /api/auth/signin
 * @accessor api.functional.api.auth.signin
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function signin(
  connection: IConnection,
  body: signin.Body,
): Promise<signin.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...signin.METADATA,
      template: signin.METADATA.path,
      path: signin.path(),
    },
    body,
  );
}
export namespace signin {
  export type Body = SignInBody;
  export type Output = SignInResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/auth/signin",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/auth/signin";
}

/**
 * @controller AuthController.signout
 * @path POST /api/auth/signout
 * @accessor api.functional.api.auth.signout
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function signout(connection: IConnection): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...signout.METADATA,
    template: signout.METADATA.path,
    path: signout.path(),
  });
}
export namespace signout {
  export const METADATA = {
    method: "POST",
    path: "/api/auth/signout",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = () => "/api/auth/signout";
}

/**
 * @controller AuthController.refresh
 * @path POST /api/auth/refresh
 * @accessor api.functional.api.auth.refresh
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function refresh(
  connection: IConnection,
): Promise<refresh.Output> {
  return PlainFetcher.fetch(connection, {
    ...refresh.METADATA,
    template: refresh.METADATA.path,
    path: refresh.path(),
  });
}
export namespace refresh {
  export type Output = SignInResponse;

  export const METADATA = {
    method: "POST",
    path: "/api/auth/refresh",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/auth/refresh";
}
